CREATE TABLE IF NOT EXISTS payment_orders (
  id                        INT UNSIGNED NOT NULL AUTO_INCREMENT,
  order_id                  VARCHAR(64) NOT NULL,
  user_id                   INT UNSIGNED NOT NULL,
  plan_code                 ENUM('starter','standard','premium') NOT NULL,
  gross_amount              INT UNSIGNED NOT NULL,
  currency                  VARCHAR(10) NOT NULL DEFAULT 'IDR',
  status                    ENUM('pending','paid','failed','expired','cancelled') NOT NULL DEFAULT 'pending',
  snap_token                VARCHAR(255) NULL,
  snap_redirect_url         TEXT NULL,
  midtrans_transaction_id   VARCHAR(120) NULL,
  midtrans_order_id         VARCHAR(64) NULL,
  payment_type              VARCHAR(60) NULL,
  transaction_status        VARCHAR(60) NULL,
  fraud_status              VARCHAR(60) NULL,
  paid_at                   DATETIME NULL,
  last_notified_at          DATETIME NULL,
  raw_notification          JSON NULL,
  created_at                DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at                DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_payment_orders_order_id (order_id),
  KEY ix_payment_orders_user (user_id),
  KEY ix_payment_orders_status (status),
  CONSTRAINT fk_payment_orders_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
